import React from 'react';
import {
  AbsoluteFill,
  Sequence,
  useCurrentFrame,
  interpolate,
  spring,
  useVideoConfig,
} from 'remotion';

// Hardcoded demo data — DreamFactoryReport is Ralph's static prototype
const data = {"org":"DreamFactory","branding":{"logo_url":"https://cdn.prod.website-files.com/64ed8da8a866be7a702fbae0/64ed8da8a866be7a702fbb4b_Favicon.png","primary_color":"#e74c3c","secondary_color":"#3898ec","font":"Arial, sans-serif","company_name":"DreamFactory"},"audit":{"domain":"dreamfactory.com","score":67,"total_issues":12,"categories":{"Technical":3,"Content":4,"GEO":3,"Links":2},"top_issues":[{"priority":"P0","title":"No YouTube presence","detail":"Video content ranks 40% higher in AI citations. No YouTube channel detected."},{"priority":"P1","title":"Missing schema markup","detail":"Structured data helps AI models cite your content accurately."},{"priority":"P2","title":"Thin documentation pages","detail":"Several doc pages under 300 words — AI models skip thin content."}],"geo_factors":{"Citations":35,"Statistics":20,"Expert Quotes":15,"Schema Markup":10,"Freshness":60,"Authority Links":45},"missing_channels":["YouTube","Podcast"],"ai_citability":false},"scenes":{"opening":{"duration_seconds":4,"logo_url":"https://cdn.prod.website-files.com/64ed8da8a866be7a702fbae0/64ed8da8a866be7a702fbb4b_Favicon.png","text":"Pressroom HQ | Digital Presence Report","subtext":"dreamfactory.com"},"seo_score":{"duration_seconds":6,"score":67,"color":"amber","caption":"Above average but not AI-optimized"},"issues_breakdown":{"duration_seconds":8,"title":"WHAT WE FOUND","bars":[{"category":"Technical","count":3,"color":"#e74c3c"},{"category":"Content","count":4,"color":"#f39c12"},{"category":"GEO","count":3,"color":"#3498db"},{"category":"Links","count":2,"color":"#2ecc71"}]},"missing_channels":[{"duration_seconds":3,"channel":"YouTube","text":"NOT DETECTED BY AI SEARCH","subtext":"No YouTube presence detected — video content ranks 40% higher in AI citations"}],"geo_readiness":{"duration_seconds":6,"title":"AI CITABILITY BREAKDOWN","factors":[{"name":"Freshness","score":60,"max":100},{"name":"Authority Links","score":45,"max":100},{"name":"Citations","score":35,"max":100},{"name":"Statistics","score":20,"max":100},{"name":"Expert Quotes","score":15,"max":100},{"name":"Schema Markup","score":10,"max":100}]},"top_fixes":{"duration_seconds":8,"fixes":[{"priority":"P0","title":"Launch YouTube channel","detail":"Create video content to improve AI citation rates by 40%"},{"priority":"P1","title":"Add schema markup","detail":"Structured data helps AI models cite your content accurately"},{"priority":"P2","title":"Expand documentation","detail":"Bulk up thin pages to 500+ words with examples and data"}]},"credits":{"duration_seconds":4,"text":"This report was generated by Pressroom HQ","url":"pressroomhq.com","tagline":"Audit • Script • Graphics — all AI. Recording is yours."}},"total_duration_seconds":48};

const BRAND = data.branding;
const AUDIT = data.audit;
const SCENES = data.scenes;
const FPS = 30;

const fontStyle = { fontFamily: `'IBM Plex Mono', ${BRAND.font}` };

// --- Scene 1: Opening Card ---
function OpeningCard() {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, 20], [0, 1], { extrapolateRight: 'clamp' });
  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a', justifyContent: 'center', alignItems: 'center', ...fontStyle }}>
      {BRAND.logo_url && (
        <img src={BRAND.logo_url} style={{ width: 120, height: 120, marginBottom: 40, opacity }} />
      )}
      <div style={{ color: '#ffffff', fontSize: 48, fontWeight: 700, opacity, textAlign: 'center' }}>
        {SCENES.opening.text}
      </div>
      <div style={{ color: BRAND.primary_color, fontSize: 28, marginTop: 16, opacity, letterSpacing: 2 }}>
        {SCENES.opening.subtext}
      </div>
    </AbsoluteFill>
  );
}

// --- Scene 2: SEO Score ---
function SEOScore() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const score = SCENES.seo_score.score;
  const scoreColor = score >= 80 ? '#33ff33' : score >= 60 ? '#ffb000' : '#ff4444';

  const animatedScore = Math.round(interpolate(frame, [0, fps], [0, score], { extrapolateRight: 'clamp' }));
  const textOpacity = interpolate(frame, [fps, fps + 15], [0, 1], { extrapolateRight: 'clamp' });

  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a', justifyContent: 'center', alignItems: 'center', ...fontStyle }}>
      <div style={{ fontSize: 200, fontWeight: 900, color: scoreColor }}>{animatedScore}</div>
      <div style={{ fontSize: 32, color: '#888', letterSpacing: 6, marginTop: -10 }}>SEO SCORE</div>
      <div style={{ fontSize: 24, color: '#aaa', marginTop: 20, opacity: textOpacity }}>
        {SCENES.seo_score.caption}
      </div>
    </AbsoluteFill>
  );
}

// --- Scene 3: Issues Breakdown ---
function IssuesBreakdown() {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();
  const bars = SCENES.issues_breakdown.bars;
  const maxCount = Math.max(...bars.map(b => b.count));

  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a', padding: 80, ...fontStyle }}>
      <div style={{ fontSize: 36, color: '#ffb000', letterSpacing: 4, marginBottom: 60 }}>
        {SCENES.issues_breakdown.title}
      </div>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 30 }}>
        {bars.map((bar, i) => {
          const delay = i * 8;
          const width = interpolate(frame, [delay, delay + 20], [0, (bar.count / maxCount) * 100], { extrapolateRight: 'clamp' });
          return (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 20 }}>
              <div style={{ width: 200, color: '#ccc', fontSize: 24, textAlign: 'right' }}>{bar.category}</div>
              <div style={{ flex: 1, height: 40, backgroundColor: '#222', borderRadius: 4, overflow: 'hidden' }}>
                <div style={{ width: `${width}%`, height: '100%', backgroundColor: bar.color, borderRadius: 4, transition: 'width 0.1s' }} />
              </div>
              <div style={{ width: 50, color: '#fff', fontSize: 28, fontWeight: 700 }}>{bar.count}</div>
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
}

// --- Scene 4: Missing Channel ---
function MissingChannel({ channel }) {
  const frame = useCurrentFrame();
  const scale = spring({ frame, fps: FPS, config: { mass: 0.5, damping: 10 } });

  return (
    <AbsoluteFill style={{ backgroundColor: BRAND.primary_color, justifyContent: 'center', alignItems: 'center', ...fontStyle }}>
      <div style={{ fontSize: 120, color: '#fff', fontWeight: 900, transform: `scale(${scale})` }}>
        {channel.channel}
      </div>
      <div style={{ fontSize: 48, color: 'rgba(255,255,255,0.6)', marginTop: 10, position: 'absolute', top: '42%' }}>
        ⊘
      </div>
      <div style={{ fontSize: 32, color: '#fff', marginTop: 30, textAlign: 'center', maxWidth: 900 }}>
        {channel.text}
      </div>
      <div style={{ fontSize: 20, color: 'rgba(255,255,255,0.7)', marginTop: 12, textAlign: 'center', maxWidth: 900 }}>
        {channel.subtext}
      </div>
    </AbsoluteFill>
  );
}

// --- Scene 5: GEO Readiness ---
function GEOReadiness() {
  const frame = useCurrentFrame();
  const factors = SCENES.geo_readiness.factors;

  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a', padding: 80, ...fontStyle }}>
      <div style={{ fontSize: 36, color: '#ffb000', letterSpacing: 4, marginBottom: 50 }}>
        {SCENES.geo_readiness.title}
      </div>
      <div style={{ flex: 1, display: 'flex', flexDirection: 'column', justifyContent: 'center', gap: 24 }}>
        {factors.map((f, i) => {
          const delay = i * 6;
          const width = interpolate(frame, [delay, delay + 18], [0, (f.score / f.max) * 100], { extrapolateRight: 'clamp' });
          const barColor = f.score >= 60 ? '#33ff33' : f.score >= 30 ? '#ffb000' : '#ff4444';
          return (
            <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
              <div style={{ width: 220, color: '#aaa', fontSize: 20, textAlign: 'right' }}>{f.name}</div>
              <div style={{ flex: 1, height: 28, backgroundColor: '#1a1a1a', borderRadius: 4, overflow: 'hidden' }}>
                <div style={{ width: `${width}%`, height: '100%', backgroundColor: barColor, borderRadius: 4 }} />
              </div>
              <div style={{ width: 50, color: '#fff', fontSize: 20, fontWeight: 600 }}>{f.score}</div>
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
}

// --- Scene 6: Top 3 Fixes ---
function TopFixes() {
  const frame = useCurrentFrame();
  const fixes = SCENES.top_fixes.fixes;
  const priorityColors = { P0: '#ff4444', P1: '#ffb000', P2: '#3898ec' };

  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a', padding: 80, justifyContent: 'center', ...fontStyle }}>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
        {fixes.map((fix, i) => {
          const delay = i * 20;
          const opacity = interpolate(frame, [delay, delay + 15], [0, 1], { extrapolateRight: 'clamp' });
          const translateY = interpolate(frame, [delay, delay + 15], [30, 0], { extrapolateRight: 'clamp' });
          return (
            <div key={i} style={{ opacity, transform: `translateY(${translateY}px)`, display: 'flex', gap: 20, alignItems: 'start' }}>
              <div style={{ backgroundColor: priorityColors[fix.priority], color: '#fff', padding: '6px 14px', borderRadius: 4, fontWeight: 700, fontSize: 20 }}>
                {fix.priority}
              </div>
              <div>
                <div style={{ color: '#fff', fontSize: 28, fontWeight: 600 }}>{fix.title}</div>
                <div style={{ color: '#999', fontSize: 20, marginTop: 6 }}>{fix.detail}</div>
              </div>
            </div>
          );
        })}
      </div>
    </AbsoluteFill>
  );
}

// --- Scene 7: Credits ---
function Credits() {
  const frame = useCurrentFrame();
  const opacity = interpolate(frame, [0, 20], [0, 1], { extrapolateRight: 'clamp' });

  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a', justifyContent: 'center', alignItems: 'center', ...fontStyle }}>
      <div style={{ opacity, textAlign: 'center' }}>
        <div style={{ fontSize: 36, color: '#fff', marginBottom: 20 }}>{SCENES.credits.text}</div>
        <div style={{ fontSize: 28, color: '#ffb000', letterSpacing: 3 }}>{SCENES.credits.url}</div>
        <div style={{ fontSize: 18, color: '#666', marginTop: 30, maxWidth: 700 }}>{SCENES.credits.tagline}</div>
      </div>
    </AbsoluteFill>
  );
}

// --- Main Composition ---
export default function DreamFactoryReport() {
  // Scene durations in frames (at 30fps)
  const s = (seconds) => seconds * FPS;

  let offset = 0;
  const seq = (duration, Component, props = {}) => {
    const el = (
      <Sequence key={offset} from={offset} durationInFrames={s(duration)}>
        <Component {...props} />
      </Sequence>
    );
    offset += s(duration);
    return el;
  };

  return (
    <AbsoluteFill style={{ backgroundColor: '#0a0a0a' }}>
      {seq(4, OpeningCard)}
      {seq(6, SEOScore)}
      {seq(8, IssuesBreakdown)}
      {SCENES.missing_channels.map((ch, i) => seq(3, MissingChannel, { channel: ch, key: i }))}
      {seq(6, GEOReadiness)}
      {seq(8, TopFixes)}
      {seq(4, Credits)}
    </AbsoluteFill>
  );
}
