"""YouTube Publish — upload videos with metadata from YouTubeScript."""

import json
import logging
import os
from pathlib import Path

from fastapi import APIRouter, Depends, UploadFile, File, Form
from fastapi.responses import JSONResponse
from sqlalchemy import select

from database import get_data_layer
from models import YouTubeScript
from services.data_layer import DataLayer

log = logging.getLogger("pressroom")

router = APIRouter(prefix="/api/youtube", tags=["youtube-publish"])

YOUTUBE_CLIENT_ID = os.getenv("YOUTUBE_CLIENT_ID", "")
YOUTUBE_CLIENT_SECRET = os.getenv("YOUTUBE_CLIENT_SECRET", "")
YOUTUBE_REFRESH_TOKEN = os.getenv("YOUTUBE_REFRESH_TOKEN", "")


def _get_youtube_service():
    """Build authenticated YouTube Data API v3 service."""
    if not YOUTUBE_CLIENT_ID or not YOUTUBE_CLIENT_SECRET or not YOUTUBE_REFRESH_TOKEN:
        return None

    from google.oauth2.credentials import Credentials
    from googleapiclient.discovery import build

    creds = Credentials(
        token=None,
        refresh_token=YOUTUBE_REFRESH_TOKEN,
        token_uri="https://oauth2.googleapis.com/token",
        client_id=YOUTUBE_CLIENT_ID,
        client_secret=YOUTUBE_CLIENT_SECRET,
    )
    return build("youtube", "v3", credentials=creds)


@router.post("/publish")
async def publish_to_youtube(
    script_id: int = Form(...),
    video: UploadFile = File(...),
    dl: DataLayer = Depends(get_data_layer),
):
    """Upload a video to YouTube using metadata from a YouTubeScript.

    Requires YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, YOUTUBE_REFRESH_TOKEN env vars.
    """
    # Get script
    result = await dl.session.execute(select(YouTubeScript).where(YouTubeScript.id == script_id))
    script = result.scalars().first()
    if not script:
        return JSONResponse(status_code=404, content={"error": "Script not found"})

    youtube = _get_youtube_service()
    if not youtube:
        return JSONResponse(status_code=503, content={
            "error": "YouTube credentials not configured. Set YOUTUBE_CLIENT_ID, YOUTUBE_CLIENT_SECRET, YOUTUBE_REFRESH_TOKEN."
        })

    # Build description with chapters
    desc = script.metadata_description or ""
    try:
        sections = json.loads(script.sections or "[]")
        if sections:
            chapters = "\n---\nChapters:\n"
            for s in sections:
                start = s.get("start_second", 0)
                mins, secs = divmod(start, 60)
                chapters += f"{mins}:{secs:02d} {s.get('heading', '')}\n"
            desc += chapters
    except (json.JSONDecodeError, TypeError):
        pass

    if "pressroomhq.com" not in desc:
        desc += "\n\n---\nScript and graphics generated by Pressroom HQ | pressroomhq.com"

    # Parse tags
    try:
        tags = json.loads(script.metadata_tags or "[]")
    except (json.JSONDecodeError, TypeError):
        tags = []

    # Save uploaded file temporarily
    tmp_path = Path(f"/tmp/pressroom_upload_{script_id}.mp4")
    try:
        content = await video.read()
        tmp_path.write_bytes(content)

        from googleapiclient.http import MediaFileUpload

        body = {
            "snippet": {
                "title": script.metadata_title or script.title or "Untitled",
                "description": desc,
                "tags": tags[:30],
                "categoryId": "28",  # Science & Technology
            },
            "status": {
                "privacyStatus": "private",  # Start private — Captain reviews
                "selfDeclaredMadeForKids": False,
            },
        }

        media = MediaFileUpload(str(tmp_path), mimetype="video/mp4", resumable=True)
        request = youtube.videos().insert(part="snippet,status", body=body, media_body=media)

        response = None
        while response is None:
            _, response = request.next_chunk()

        video_id = response.get("id", "")
        youtube_url = f"https://youtube.com/watch?v={video_id}" if video_id else ""

        # Update script status
        script.status = "published"
        await dl.commit()

        return {
            "youtube_url": youtube_url,
            "video_id": video_id,
            "status": "uploaded",
            "privacy": "private",
        }

    except Exception as e:
        log.error("YouTube upload failed: %s", e)
        return JSONResponse(status_code=500, content={"error": f"Upload failed: {str(e)}"})
    finally:
        if tmp_path.exists():
            tmp_path.unlink()
